set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'rust-lang/rust.vim'
Plugin 'timonv/vim-cargo'

call vundle#end()
filetype plugin indent on

syntax on

set autoindent
set t_Co=256
colorscheme calmdown
set autowrite
set sw=4
set notextmode
set hlsearch
set incsearch
set shell=bash\ --login
set tabstop=4 softtabstop=0 expandtab shiftwidth=4 smarttab
set nu

set noeb vb t_vb=
au GUIEnter * set vb t_vb=
au InsertEnter,InsertLeave * set cul!

let g:netrw_banner = 0

nnoremap <leader>\ :noh<cr>
nnoremap <leader>s :update<cr>
nnoremap <leader>b :sh<cr>
nnoremap <leader>h :tabe %:p:s,.h$,.X123X,:s,.cpp$,.h,:s,.X123X$,.cpp,<cr>
nnoremap <leader>d :tabe .<cr>
nnoremap <leader>q :q<cr>
